WebAppASPCore1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebAppASPCore1.Home.ViewModel;
using WebAppASPCore1.Model;
using WebAppASPCore1.Services;

namespace WebAppASPCore1.Controllers
{
    public class HomeController : Controller
    {
        private IDeveloperData _developers;
        private ICompany _company;

        public HomeController(IDeveloperData developers,
            ICompany company)
        {
            _developers = developers;
            _company = company;
        }
        public IActionResult Index()
        {
            var model = _developers.GetDevelopers().Where(d => d.Id > 0);
            var vModel = new HomeIndexVM() { Developers = model, CompanyMessage = _company.GetMessageOfTheDay() };

            return View(vModel);
        }

        public IActionResult Details(int id)
        {
            var model = _developers.GetDevelopers().FirstOrDefault(d => d.Id == id);
            if (model == null)
                return RedirectToAction(nameof(Index));
            else
                return View(model);
            
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(HomeDeveloperVM devVM)
        {
            if (ModelState.IsValid)
            { 
                var newDev = new Developer()
                {
                    Name = devVM.Name,
                    Age = devVM.Age,
                    TypeOfDev = devVM.TypeOfDev,
                    Address = devVM.Address
                };

                newDev = _developers.Add(newDev);

                return RedirectToAction(nameof(Details), new { id = newDev.Id });
            }
            else
            {
                return View();
            }
        }
    }
}

WebAppASPCore1/Pages/Company.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppASPCore1.Services;

namespace WebAppASPCore1.Pages
{
    public class CompanyModel : PageModel
    {
        private ICompany _company;

        public CompanyModel(ICompany company)
        {
            _company = company;
        }

        public string CompanyMessageForTheDay { get; private set; }

        public void OnGet(string name)
        {
            CompanyMessageForTheDay = $"{name} : {_company.GetMessageOfTheDay()}";
        }
    }
}

WebAppASPCore1/Pages/Developers/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppASPCore1.Model;
using WebAppASPCore1.Services;

namespace WebAppASPCore1.Pages.Developers
{
    public class EditModel : PageModel
    {
        private IDeveloperData _developerData;

        public EditModel(IDeveloperData devData)
        {
            _developerData = devData;
        }

        [BindProperty]
        public Developer Developer { get;  set; }

        public IActionResult OnGet(int Id)
        {
            Developer = _developerData.Get(Id);

            if (Developer == null)
                return RedirectToAction("Index", "Home");
            else
                return Page();

        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                Developer = _developerData.Update(Developer);
                return RedirectToAction("Details", "Home", new { id = Developer.Id });
            }
            return Page();
        }
    }
}

WebAppASPCore1/ViewComponents/CompanyMsgViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppASPCore1.Services;

namespace WebAppASPCore1.ViewComponents
{
    public class CompanyMsgViewComponent : ViewComponent
    {
        private ICompany _company;

        public CompanyMsgViewComponent(ICompany company)
        {
            _company = company; 
        }

        public IViewComponentResult Invoke()
        {
            var model = _company.GetMessageOfTheDay();
            return View("Default", model);
        }
    }
}

WebAppASPCore1/Pages/Company.cshtml
@page "{name}"
@model CompanyModel

<div>@Model.CompanyMessageForTheDay</div>

WebAppASPCore1/Pages/Developers/Edit.cshtml
@page "{Id}"
@using WebAppASPCore1.Pages.Developers;
@model EditModel

<h1>Edit @Model.Developer.Name</h1>
<form method="post">
    <input type="hidden" asp-for="Developer.Id" />

    <div>
        <label asp-for="Developer.Name"></label>
        <input asp-for="Developer.Name" />
        <span asp-validation-for="Developer.Name"></span>
    </div>
    <div>
        <label asp-for="Developer.Age"></label>
        <input asp-for="Developer.Age" />
        <span asp-validation-for="Developer.Age"></span>
    </div>
    <div>
        <label asp-for="Developer.Address"></label>
        <input asp-for="Developer.Address" />
        <span asp-validation-for="Developer.Address"></span>
    </div>
    <div>
        <label asp-for="Developer.TypeOfDev"></label>
        <select asp-for="Developer.TypeOfDev" asp-items="Html.GetEnumSelectList<eDeveloperType>()"></select>
        <span asp-validation-for="Developer.TypeOfDev"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>

WebAppASPCore1/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required:false)
    </footer>
    <div>@DateTime.Now</div>
</body>
</html>

WebAppASPCore1/Views/Home/Create.cshtml
@model HomeDeveloperVM

@{ 
    ViewBag.Title = "Create Developer";
}
<form method="post">
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <label asp-for="Age"></label>
        <input asp-for="Age" />
        <span asp-validation-for="Age"></span>
    </div>
    <div>
        <label asp-for="Address"></label>
        <input asp-for="Address" />
        <span asp-validation-for="Address"></span>
    </div>
    <div>
        <label asp-for="TypeOfDev"></label>
        <select asp-for="TypeOfDev" asp-items="Html.GetEnumSelectList<eDeveloperType>()"></select>
        <span asp-validation-for="TypeOfDev"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>

WebAppASPCore1/Views/Home/Details.cshtml
@model Developer

@{
    ViewBag.Title = "View Details";
}

<div>
    <h4>Developer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TypeOfDev)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TypeOfDev)
        </dd>
    </dl>
    <a asp-action="Index" asp-controller="Home">Go Home</a>
</div>

@section footer {
<div>Developer Name : @Model.Name</div>
}

WebAppASPCore1/Views/Home/Index.cshtml
@model HomeIndexVM

@{
    ViewBag.Title = "Home Page";
    //Layout = "~/Views/Shared/_Layout.ckshtml";
}

<h1>All Developers</h1>

@foreach (var item in Model.Developers)
{
    @Html.Partial("_Summary", item);
}

<div><a asp-action="Create">Add Developer</a></div>

@*<div>
    @section footer {
        <h1>@Model.CompanyMessage</h1>
}
</div>*@

WebAppASPCore1/Views/Home/_Summary.cshtml
@model Developer

<section>
    <h3>@Model.Name</h3>
    
    <div>@Model.Id</div>
    <div>@Model.Age</div>
    <div>@Model.Address</div>
    <div>@Model.TypeOfDev</div>
    @*<div><a href="/home/details/@Model.Id">Detials</a></div>
    <div>@Html.ActionLink("Go", "Details", new { id = Model.Id })</div>*@
    <div>
        <a asp-action="Details" asp-route-id="@Model.Id">More</a>
        <a asp-page="/Developers/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</section>

WebAppASPCore1/Views/Shared/Components/CompanyMsg/Default.cshtml
@model string 

<div>
    @Model
</div>

WebAppASPCore1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required:false)
        @await Component.InvokeAsync("CompanyMsg")
    </footer>
    <div>@DateTime.Now</div>
</body>
</html>